repositories {
  mavenLocal()
  mavenCentral()
}
group 'com.github.lucene-gosen'
description 'Japanese analysis for Apache Lucene/Solr'

apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'idea'

version = luceneVersion

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

dependencies {
  implementation "org.apache.lucene:lucene-core:${luceneVersion}"
  implementation "org.apache.lucene:lucene-analysis-common:${luceneVersion}"
  implementation "org.apache.lucene:lucene-codecs:${luceneVersion}"
  implementation "com.ibm.icu:icu4j:${icu4jVersion}"

  testImplementation "junit:junit:${junitVersion}"
  testImplementation "org.apache.lucene:lucene-test-framework:${luceneVersion}"
  testImplementation "com.carrotsearch.randomizedtesting:randomizedtesting-runner:${randomizedrunnerVersion}"
}

javadoc {
  options.locale = 'en_US'
}

jacocoTestReport {
  reports {
    xml.required = true
    html.required = true
  }
  afterEvaluate {
    classDirectories.setFrom(files(classDirectories.files.collect {
      fileTree(dir: it, exclude: [
        'net/java/sen/compiler/**',
        'net/java/sen/tools/**',
      ])
    }))
  }
}

jacocoTestCoverageVerification {
  afterEvaluate {
    classDirectories.setFrom(files(classDirectories.files.collect {
      fileTree(dir: it, exclude: [
        'net/java/sen/compiler/**',
        'net/java/sen/tools/**',
      ])
    }))
  }
  violationRules {
    rule {
      limit {
        minimum = 0.90
      }
    }
  }
}
defaultTasks 'clean', 'dist'

// Re-build dictionary with user custom dictionaries, without copy
task rebuildNaistChasenDic() {
  doLast {
    println "rebuilding dicitonary"
  }
}

tasks.rebuildNaistChasenDic.dependsOn(compileJava, ":dictionary:cleanCompiledNaistChasen", ":dictionary:compileNaistChasen")

task rebuildIpadicDic() {
  doLast {
    println "rebuilding dicitonary"
  }
}

tasks.rebuildIpadicDic.dependsOn(compileJava, ":dictionary:cleanCompiledIpadic", ":dictionary:compileIpadic")


// Create Jar library without dictionary
task jarWithNaistChasen(type: Jar) {
  archiveClassifier = naistDictype
  from files(sourceSets.main.output,
          fileTree("dictionary" + File.separator
            + naistDictype + File.separator + compiledDicDir).include('**/*.sen')
  )
}

tasks.jarWithNaistChasen.dependsOn(compileJava, ":dictionary:compileNaistChasen")

task jarWithIpadic(type: Jar) {
  archiveClassifier = ipadicDictype
  from files(sourceSets.main.output,
          fileTree("dictionary" + File.separator
                  + ipadicDictype + File.separator + compiledDicDir).include('**/*.sen')
  )
}

tasks.jarWithIpadic.dependsOn(compileJava, ":dictionary:compileIpadic")

task jarWithUnidic(type: Jar) {
  archiveClassifier = unidicDictype
  from files(sourceSets.main.output,
          fileTree("dictionary" + File.separator
                  + unidicDictype + File.separator + compiledDicDir).include('**/*.sen')
  )
}

tasks.jarWithUnidic.dependsOn(compileJava, ":dictionary:compileUnidic")

task javadocJar(type: Jar) {
  archiveClassifier = 'javadoc'
  from javadoc
}

task sourcesJar(type: Jar) {
  archiveClassifier = 'sources'
  from sourceSets.main.allSource
}

// Make packages for distribution
task dist(dependsOn: [jar, jarWithIpadic, jarWithNaistChasen, test]) {
}

tasks.test.dependsOn(compileJava, ":dictionary:compileNaistChasen", ":dictionary:compileIpadic")

if (gradle.startParameter.taskNames.contains('uploadArchives')) {
  apply from: 'uploadArchives.gradle'
}
