naistDictype = naist-chasen
ipadicDictype = ipadic
unidicDictype = unidic

# set default dictionary type
# to change the dictionary type to naist-chasen, gradle
dictype = ipadic
luceneVersion = 10.4.0
junitVersion = 4.13.2
randomizedrunnerVersion = 2.8.3
icu4jVersion = 77.1

# directories
compiledDicDir = compiled-dictionaries
