dic.home=https://clrd.ninjal.ac.jp/unidic_archive/2512
dic.version=202512
dic.archive=unidic-cwj-${dic.version}_full.zip
dic.dir=unidic-cwj-${dic.version}_full
dic.unpacked.file=unidic-cwj-${dic.version}_full/lex.csv
